apiVersion: v1
baseDomain: ibm.com
compute:
- architecture: ppc64le
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: ppc64le
  hyperthreading: Enabled
  defaultMachinePlatform:
    type: ocp4-bastion-c9a7-scg
  clusterOSImageProperties:
    architecture: 'ppc64'
    bdm_v2: 'true'
    block_device_mapping: '[{"boot_index":0,"volume_size":"120","device_type":"disk","destination_type":"volume","source_type":"blank"}]'
    endianness: 'little-endian'
    hypervisor_type: 'phyp'
    os_distro: 'rhel'
  rootVolume:
    size: 120
    type: "V7K base template"
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: christy-pvc
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  openstack:
    apiVIP: 10.0.0.5
    cloud: scnl_powervc
    defaultMachinePlatform:
      type: ocp4-bastion-c9a7-scg
    externalDNS: null
    clusterOSImage: file:///home/christy/hacky/powervc-installer/unzipped_img/rhcos-46.82.202010030041-0-qemu.ppc64le.raw.gz
    clusterOSImageProperties:
      architecture: 'ppc64'
      bdm_v2: 'true'
      block_device_mapping: '[{"guest_format":null,"boot_index":0,"no_device":null,"image_id":null, "disk_bus":null,"volume_size":"120","device_type":"disk","snapshot_id":null, "source_type":"blank", "destination_type":"volume","delete_on_termination":true}]'
      endianness: 'little-endian'
      hypervisor_type: 'phyp'
      os_distro: 'rhel'
    rootVolume:
      size: 120
      type: "V7K base template"
    ingressVIP: 10.0.0.7
publish: External
pullSecret:
sshKey: |
